version: '3.4'

services:

  ascustomer:
    # Use a static website hosting service in production
    build:
      context: ./ascustomer
    volumes:
      - ./asCustomer:/usr/src/asCustomer:rw,cached
      - /usr/src/asCustomer/node_modules
    ports:
      - "8080:8080"

  mercure:
    image: dunglas/mercure:latest
    env_file:
      - ./mercure/.env
    ports:
      - "8081:8081"

  h2-proxy:
    # Don't use this proxy in prod
    build:
      context: h2-proxy
    depends_on:
      - ascustomer
    ports:
      - "80:80"
      - "443:443"
